version: "3.8"
services:
  web:
    build: ./ui
    container_name: ui
    ports:
      - "8083:8083"
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    container_name: server
    ports:
      - "8084:8084"
    volumes:
      - ./server:/server
    stdin_open: true
    tty: true
